spring.application.name=Restaurante
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/restaurant
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update
jwt.secret=miClaveSecretaSuperSegura12345678asdasdasd21548asd15486542154asd8452154ad564812214456564789
jwt.expiration=86400000
